#@ load("@ytt:data", "data")
#@ load("helpers.lib.yml", "manage_gcp_dns", "delete_deployment")

---
groups:
- name: update-releases
  jobs:
  #@ for r in data.values.baseReleases:
  - #@ "update-" + r.name
  #@ end

resources:
#@ for r in data.values.baseReleases:
- name: #@ r.name + "-release"
  type: bosh-io-release
  source:
    repository: #@ r.repository
#@ end

- name: cf-deployment-release-candidate
  type: git
  source:
    branch: release-candidate
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: relint-envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

jobs:
#@ for r in data.values.baseReleases:
- name: #@ "update-" + r.name
  serial_groups:
  - update-release
  public: true
  plan:
  - aggregate:
    - get: #@ r.name + "-release"
      trigger: true
      params:
        tarball: false
    - get: cf-deployment-release-candidate
    - get: stemcell
      params:
        tarball: false
    - get: cf-deployment-concourse-tasks
    - get: runtime-ci
    - get: relint-envs
  - task: #@ "update-release-" + r.name
    file: runtime-ci/tasks/update-single-manifest-release/task.yml
    input_mapping:
      deployment-configuration: cf-deployment-release-candidate
      release: #@ r.name + "-release"
    params:
      RELEASE_NAME: #@ r.name
  - task: #@ "update-additional-ops-files-" + r.name
    file: runtime-ci/tasks/update-single-opsfile-release/task.yml
    input_mapping:
      current-commit-message: commit-message
      original-ops-file: cf-deployment-release-candidate
      release: #@ r.name + "-release"
    params:
      RELEASE_NAME: #@ r.name
  - do:
    - task: bbl-up
      file: cf-deployment-concourse-tasks/bbl-up/task.yml
      params:
        BBL_STATE_DIR: environments/test/pre-dev/bbl-state
        BBL_IAAS: gcp
        BBL_ENV_NAME: pre-dev
        BBL_GCP_SERVICE_ACCOUNT_KEY: environments/test/pre-dev/google_account_creds.json
        BBL_GCP_REGION: us-central1
        BBL_LB_CERT: ((pre_dev_cf_lb_cert.certificate))
        BBL_LB_KEY: ((pre_dev_cf_lb_cert.private_key))
        LB_DOMAIN: pre-dev.test.relint.rocks
      input_mapping:
        bbl-state: relint-envs
        bbl-config: relint-envs
      ensure:
        put: relint-envs
        params:
          repository: updated-bbl-state
          rebase: true
    - #@ manage_gcp_dns("add")
    - task: deploy-cf
      file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
      input_mapping:
        bbl-state: relint-envs
        cf-deployment: updated-deployment-manifest
        ops-files: cf-deployment-release-candidate
        vars-files: relint-envs
      params:
        BBL_STATE_DIR: environments/test/pre-dev/bbl-state
        SYSTEM_DOMAIN: pre-dev.test.relint.rocks
        OPS_FILES: |
          operations/experimental/fast-deploy-with-downtime-and-danger.yml
        REGENERATE_CREDENTIALS: false
        BOSH_DEPLOY_ARGS: "--parallel 50"
    - task: commit-generated-manifest-and-ops
      file: runtime-ci/tasks/commit-generated-manifest/task.yml
      input_mapping:
        manifest: updated-deployment-manifest
        ops-file: updated-ops-file
        repo: cf-deployment-release-candidate
      params:
        COMMIT_ALL_OPS_FILES: true
        MANIFEST_DESTINATION: cf-deployment.yml
        MANIFEST_NAME: cf-deployment.yml
    ensure:
      do:
      - #@ delete_deployment("pre-dev")
      - #@ manage_gcp_dns("remove")
      - task: bbl-down
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        input_mapping:
          bbl-state: relint-envs
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: environments/test/pre-dev/google_account_creds.json
          BBL_STATE_DIR: environments/test/pre-dev/bbl-state
        ensure:
          put: relint-envs
          params:
            repository: updated-bbl-state
            rebase: true

#@ end
