#@ load("@ytt:data", "data")

---
groups:
- name: update-releases
  jobs:
  - deploy
  #@ for r in data.values.baseReleases:
  - #@ "update-" + r.name
  #@ end

resources:
#@ for r in data.values.baseReleases:
- name: #@ r.name + "-release"
  type: bosh-io-release
  source:
    repository: #@ r.repository
#@ end

- name: cf-deployment-release-candidate
  type: git
  source:
    branch: release-candidate
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: relint-envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

jobs:
#@ for r in data.values.baseReleases:
- name: #@ "update-" + r.name
  serial_groups:
  - update-release
  public: true
  plan:
  - aggregate:
    - get: #@ r.name + "-release"
      trigger: true
      params:
        tarball: false
    - get: cf-deployment-release-candidate
    - get: stemcell
      params:
        tarball: false
    - get: cf-deployment-concourse-tasks
    - get: runtime-ci
    - get: relint-envs
  - task: #@ "update-release-" + r.name
    file: runtime-ci/tasks/update-single-manifest-release/task.yml
    input_mapping:
      release: #@ r.name + "-release"
      deployment-configuration: cf-deployment-release-candidate
    params:
      RELEASE_NAME: #@ r.name
  #@ if r.name.count("buildpack")==0:
  - task: bosh-dry-run
    file: runtime-ci/tasks/bosh-dry-run-with-ops/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: updated-deployment-manifest
      ops-files: cf-deployment-release-candidate
      #@ if hasattr(r, "varsFilesInput"):
      vars-files: #@ r.varsFilesInput
      #@ else:
      vars-files: relint-envs
      #@ end
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      DEPLOYMENT_NAME_SUFFIX: #@ r.name + "-pre-dev"
      SYSTEM_DOMAIN: greengrass.cf-app.com
  - task: bosh-delete-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      DEPLOYMENT_NAME: #@ "cf-dry-run-" + r.name + "-pre-dev"
  #@ end
  - task: commit-generated-manifest-and-ops
    file: runtime-ci/tasks/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-release-candidate
      manifest: updated-deployment-manifest
      ops-file: cf-deployment-release-candidate
    params:
      MANIFEST_NAME: cf-deployment.yml
      MANIFEST_DESTINATION: cf-deployment.yml
#@ end

- name: deploy
  serial_groups:
  - update-release
  public: true
  plan:
  - aggregate:
    - get: cf-deployment-release-candidate
      passed:
      #@ for r in data.values.baseReleases:
      - #@ "update-" + r.name
      #@ end
    - get: cf-deployment-concourse-tasks
    - get: runtime-ci
    - get: relint-envs
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_STATE_DIR: environments/test/pre-dev/bbl-state
      BBL_IAAS: gcp
      BBL_ENV_NAME: pre-dev
      BBL_GCP_SERVICE_ACCOUNT_KEY: environments/test/pre-dev/google_account_creds.json
      BBL_GCP_REGION: us-central1
      BBL_LB_CERT: ((pre_dev_cf_lb_cert.certificate))
      BBL_LB_KEY: ((pre_dev_cf_lb_cert.private_key))
      LB_DOMAIN: pre-dev.cf-app.com
    input_mapping:
      bbl-state: relint-envs
      bbl-config: bosh-bootloader
    ensure:
      put: relint-envs
      params:
        repository: updated-bbl-state
        rebase: true
  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: cf-deployment-release-candidate
      vars-files: relint-envs
    params:
      BBL_STATE_DIR: environments/test/pre-dev/bbl-state
      SYSTEM_DOMAIN: pre-dev.cf-app.com
      OPS_FILES: |
        operations/experimental/fast-deploy-with-downtime-and-danger.yml
        operations/use-compiled-releases.yml
  - task: ensure-gcloud-backend-service-healthy
    file: runtime-ci/tasks/ensure-gcloud-backend-service-healthy/task.yml
    input_mapping:
      google-creds-dir: relint-envs
    params:
      GCP_PROJECT_ID: ((pre_dev_gcp_project))
      GCP_BACKEND_SERVICE: ((pre_dev_router_backend_service))
      GOOGLE_ACCOUNT_CREDS_PATH: environments/test/pre-dev/google_account_creds.json
  - task: ensure-api-healthy
    file: runtime-ci/tasks/ensure-api-healthy/task.yml
    input_mapping:
      cats-integration-config: relint-envs
    params:
      CONFIG_FILE_PATH: environments/test/pre-dev/integration_config.json
